--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaDevGuy/EpikFly
build-by-default: true
branches:
- main
projects:
  EpikFly:
    path: ""
    libs:
      - src: jojoe77777\FormAPI\FormAPI
        version: ^2.1.0
        branch: stable
    lints:
     phpstan: false
...
